#define YTT_GROUPLEFTPAREN                  1
#define YTT_LEFTPAREN                       2
#define YTT_SCOPESTARTBLOCK                 3
#define YTT_STARTBLOCK                      4
#define YTT_NEGATIVE                        5
#define YTT_DASH                            6
#define YTT_NEWLINE                         7
#define YTT_SEMI                            8
#define YTT_ASSIGN                          9
#define YTT_QUESTIONMARK                   10
#define YTT_COLON                          11
#define YTT_IF                             12
#define YTT_ELSE                           13
#define YTT_HEREDOC                        14
#define YTT_ELLIPSIS                       15
#define YTT_BREAK                          16
#define YTT_THIS                           17
#define YTT_UNKNOWN                        18
#define YTT_COMMENT                        19
#define YTT_SPACE                          20
#define YTT_EOF                            21
#define YTT_BITWISE_OREQUALS               22
#define YTT_BITWISE_XOREQUALS              23
#define YTT_BITWISE_ANDEQUALS              24
#define YTT_SHIFTRIGHTEQUALS               25
#define YTT_SHIFTLEFTEQUALS                26
#define YTT_PLUSEQUALS                     27
#define YTT_SLASHEQUALS                    28
#define YTT_DASHEQUALS                     29
#define YTT_STAREQUALS                     30
#define YTT_OR                             31
#define YTT_BITWISE_OR                     32
#define YTT_BITWISE_XOR                    33
#define YTT_AND                            34
#define YTT_BITWISE_AND                    35
#define YTT_BITWISE_NOT                    36
#define YTT_NOT                            37
#define YTT_EQUALS                         38
#define YTT_NOTEQUALS                      39
#define YTT_CMP                            40
#define YTT_LESSTHAN                       41
#define YTT_LESSTHANOREQUAL                42
#define YTT_GREATERTHAN                    43
#define YTT_GREATERTHANOREQUAL             44
#define YTT_INHERITS                       45
#define YTT_SHIFTRIGHT                     46
#define YTT_SHIFTLEFT                      47
#define YTT_PLUS                           48
#define YTT_STAR                           49
#define YTT_SLASH                          50
#define YTT_MOD                            51
#define YTT_PERIOD                         52
#define YTT_COLONCOLON                     53
#define YTT_OPENBRACE                      54
#define YTT_CLOSEBRACE                     55
#define YTT_OPENBRACKET                    56
#define YTT_CLOSEBRACKET                   57
#define YTT_ENDBLOCK                       58
#define YTT_ENDSTATEMENT                   59
#define YTT_RETURN                         60
#define YTT_WHILE                          61
#define YTT_FUNCTION                       62
#define YTT_IDENTIFIER                     63
#define YTT_RIGHTPAREN                     64
#define YTT_FOR                            65
#define YTT_IN                             66
#define YTT_COMMA                          67
#define YTT_FATCOMMA                       68
#define YTT_INTEGER                        69
#define YTT_FLOATNUM                       70
#define YTT_LITERALSTRING                  71
#define YTT_NULL                           72
#define YTT_VAR                            73
