#define ETT_GROUPLEFTPAREN                  1
#define ETT_LEFTPAREN                       2
#define ETT_SCOPESTARTBLOCK                 3
#define ETT_STARTBLOCK                      4
#define ETT_NEGATIVE                        5
#define ETT_DASH                            6
#define ETT_NEWLINE                         7
#define ETT_SEMI                            8
#define ETT_ASSIGN                          9
#define ETT_QUESTIONMARK                   10
#define ETT_COLON                          11
#define ETT_IF                             12
#define ETT_ELSE                           13
#define ETT_HEREDOC                        14
#define ETT_ELLIPSIS                       15
#define ETT_BREAK                          16
#define ETT_THIS                           17
#define ETT_UNKNOWN                        18
#define ETT_COMMENT                        19
#define ETT_SPACE                          20
#define ETT_EOF                            21
#define ETT_BITWISE_OREQUALS               22
#define ETT_BITWISE_XOREQUALS              23
#define ETT_BITWISE_ANDEQUALS              24
#define ETT_SHIFTRIGHTEQUALS               25
#define ETT_SHIFTLEFTEQUALS                26
#define ETT_PLUSEQUALS                     27
#define ETT_SLASHEQUALS                    28
#define ETT_DASHEQUALS                     29
#define ETT_STAREQUALS                     30
#define ETT_OR                             31
#define ETT_BITWISE_OR                     32
#define ETT_BITWISE_XOR                    33
#define ETT_AND                            34
#define ETT_BITWISE_AND                    35
#define ETT_BITWISE_NOT                    36
#define ETT_NOT                            37
#define ETT_EQUALS                         38
#define ETT_NOTEQUALS                      39
#define ETT_CMP                            40
#define ETT_LESSTHAN                       41
#define ETT_LESSTHANOREQUAL                42
#define ETT_GREATERTHAN                    43
#define ETT_GREATERTHANOREQUAL             44
#define ETT_INHERITS                       45
#define ETT_SHIFTRIGHT                     46
#define ETT_SHIFTLEFT                      47
#define ETT_PLUS                           48
#define ETT_STAR                           49
#define ETT_SLASH                          50
#define ETT_MOD                            51
#define ETT_PERIOD                         52
#define ETT_COLONCOLON                     53
#define ETT_OPENBRACE                      54
#define ETT_CLOSEBRACE                     55
#define ETT_OPENBRACKET                    56
#define ETT_CLOSEBRACKET                   57
#define ETT_ENDBLOCK                       58
#define ETT_ENDSTATEMENT                   59
#define ETT_RETURN                         60
#define ETT_WHILE                          61
#define ETT_FUNCTION                       62
#define ETT_IDENTIFIER                     63
#define ETT_RIGHTPAREN                     64
#define ETT_FOR                            65
#define ETT_IN                             66
#define ETT_COMMA                          67
#define ETT_FATCOMMA                       68
#define ETT_INTEGER                        69
#define ETT_FLOATNUM                       70
#define ETT_LITERALSTRING                  71
#define ETT_NULL                           72
#define ETT_VAR                            73
