#define YTT_GROUPLEFTPAREN                  1
#define YTT_LEFTPAREN                       2
#define YTT_SCOPESTARTBLOCK                 3
#define YTT_STARTBLOCK                      4
#define YTT_NEGATIVE                        5
#define YTT_DASH                            6
#define YTT_HEREDOC                         7
#define YTT_ELLIPSIS                        8
#define YTT_BREAK                           9
#define YTT_BITWISE_OREQUALS               10
#define YTT_BITWISE_ANDEQUALS              11
#define YTT_BITWISE_XOREQUALS              12
#define YTT_PLUSEQUALS                     13
#define YTT_DASHEQUALS                     14
#define YTT_STAREQUALS                     15
#define YTT_SLASHEQUALS                    16
#define YTT_SHIFTRIGHTEQUALS               17
#define YTT_SHIFTLEFTEQUALS                18
#define YTT_NEWLINE                        19
#define YTT_OPENBRACE                      20
#define YTT_CLOSEBRACE                     21
#define YTT_OPENBRACKET                    22
#define YTT_CLOSEBRACKET                   23
#define YTT_SEMI                           24
#define YTT_ASSIGN                         25
#define YTT_CMP                            26
#define YTT_EQUALS                         27
#define YTT_NOTEQUALS                      28
#define YTT_LESSTHAN                       29
#define YTT_LESSTHANOREQUAL                30
#define YTT_GREATERTHAN                    31
#define YTT_GREATERTHANOREQUAL             32
#define YTT_INHERITS                       33
#define YTT_PERIOD                         34
#define YTT_COLONCOLON                     35
#define YTT_QUESTIONMARK                   36
#define YTT_COLON                          37
#define YTT_UNKNOWN                        38
#define YTT_COMMENT                        39
#define YTT_SPACE                          40
#define YTT_EOF                            41
#define YTT_BITWISE_OR                     42
#define YTT_BITWISE_AND                    43
#define YTT_BITWISE_XOR                    44
#define YTT_BITWISE_NOT                    45
#define YTT_SHIFTRIGHT                     46
#define YTT_SHIFTLEFT                      47
#define YTT_PLUS                           48
#define YTT_STAR                           49
#define YTT_SLASH                          50
#define YTT_AND                            51
#define YTT_OR                             52
#define YTT_THIS                           53
#define YTT_NOT                            54
#define YTT_MOD                            55
#define YTT_IF                             56
#define YTT_ELSE                           57
#define YTT_ENDBLOCK                       58
#define YTT_ENDSTATEMENT                   59
#define YTT_RETURN                         60
#define YTT_WHILE                          61
#define YTT_FUNCTION                       62
#define YTT_IDENTIFIER                     63
#define YTT_RIGHTPAREN                     64
#define YTT_FOR                            65
#define YTT_IN                             66
#define YTT_COMMA                          67
#define YTT_FATCOMMA                       68
#define YTT_INTEGER                        69
#define YTT_FLOATNUM                       70
#define YTT_LITERALSTRING                  71
#define YTT_NULL                           72
#define YTT_VAR                            73
